[project]
name = "ha-log-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.70.0",
    "python-dotenv>=1.1.0",
    "streamlit>=1.44.1",
]
