summarize_logs:
  description: Analyze the specified Home Assistant log file using GPT
  fields:
    file_path:
      description: Optional path to the log file to analyze
      example: "/config/home-assistant.log"
      required: false
      selector:
        text: